apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-test-app-config
  labels:
    app: sre-test-app
data:
  APP_VERSION: {{ .Values.app.version | quote }}
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}

