replicaCount: 2

image:
  repository: ashiqali246/sre-test-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

app:
  version: "1.0.0"
  environment: "production"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 5

ingress:
  enabled: true
  className: traefik
  host: sre-app.local

appSecret: ""
